const List<Map<String, String>> countries = [
  {
    "id": "0",
    "name": "افغانستان",
    "code": "AF",
    "dial_code": "+93",
    "flag": "🇦🇫",
  },
  {
    "id": "1",
    "name": "Åland",
    "code": "AX",
    "dial_code": "+358",
    "flag": "🇦🇽",
  },
  {
    "id": "2",
    "name": "Shqipëria",
    "code": "AL",
    "dial_code": "+355",
    "flag": "🇦🇱",
  },
  {
    "id": "3",
    "name": "الجزائر",
    "code": "DZ",
    "dial_code": "+213",
    "flag": "🇩🇿",
  },
  {
    "id": "4",
    "name": "American Samoa",
    "code": "AS",
    "dial_code": "+1684",
    "flag": "🇦🇸",
  },
  {
    "id": "5",
    "name": "Andorra",
    "code": "AD",
    "dial_code": "+376",
    "flag": "🇦🇩",
  },
  {
    "id": "6",
    "name": "Angola",
    "code": "AO",
    "dial_code": "+244",
    "flag": "🇦🇴",
  },
  {
    "id": "7",
    "name": "Anguilla",
    "code": "AI",
    "dial_code": "+1264",
    "flag": "🇦🇮",
  },
  {
    "id": "8",
    "name": "Antarctica",
    "code": "AQ",
    "dial_code": "+672",
    "flag": "🇦🇶",
  },
  {
    "id": "9",
    "name": "Antigua and Barbuda",
    "code": "AG",
    "dial_code": "+1268",
    "flag": "🇦🇬",
  },
  {
    "id": "10",
    "name": "Argentina",
    "code": "AR",
    "dial_code": "+54",
    "flag": "🇦🇷",
  },
  {
    "id": "11",
    "name": "Հայաստան",
    "code": "AM",
    "dial_code": "+374",
    "flag": "🇦🇲",
  },
  {
    "id": "12",
    "name": "Aruba",
    "code": "AW",
    "dial_code": "+297",
    "flag": "🇦🇼",
  },
  {
    "id": "13",
    "name": "Australia",
    "code": "AU",
    "dial_code": "+61",
    "flag": "🇦🇺",
  },
  {
    "id": "14",
    "name": "Österreich",
    "code": "AT",
    "dial_code": "+43",
    "flag": "🇦🇹",
  },
  {
    "id": "15",
    "name": "Azərbaycan",
    "code": "AZ",
    "dial_code": "+994",
    "flag": "🇦🇿",
  },
  {
    "id": "16",
    "name": "Bahamas",
    "code": "BS",
    "dial_code": "+1242",
    "flag": "🇧🇸",
  },
  {
    "id": "17",
    "name": "‏البحرين",
    "code": "BH",
    "dial_code": "+973",
    "flag": "🇧🇭",
  },
  {
    "id": "18",
    "name": "Bangladesh",
    "code": "BD",
    "dial_code": "+880",
    "flag": "🇧🇩",
  },
  {
    "id": "19",
    "name": "Barbados",
    "code": "BB",
    "dial_code": "+1246",
    "flag": "🇧🇧",
  },
  {
    "id": "20",
    "name": "Белару́сь",
    "code": "BY",
    "dial_code": "+375",
    "flag": "🇧🇾",
  },
  {
    "id": "21",
    "name": "België",
    "code": "BE",
    "dial_code": "+32",
    "flag": "🇧🇪",
  },
  {
    "id": "22",
    "name": "Belize",
    "code": "BZ",
    "dial_code": "+501",
    "flag": "🇧🇿",
  },
  {
    "id": "23",
    "name": "Bénin",
    "code": "BJ",
    "dial_code": "+229",
    "flag": "🇧🇯",
  },
  {
    "id": "24",
    "name": "Bermuda",
    "code": "BM",
    "dial_code": "+1441",
    "flag": "🇧🇲",
  },
  {
    "id": "25",
    "name": "ʼbrug-yul",
    "code": "BT",
    "dial_code": "+975",
    "flag": "🇧🇹",
  },
  {
    "id": "26",
    "name": "Bolivia",
    "code": "BO",
    "dial_code": "+591",
    "flag": "🇧🇴",
  },
  {
    "id": "27",
    "name": "Bosna i Hercegovina",
    "code": "BA",
    "dial_code": "+387",
    "flag": "🇧🇦",
  },
  {
    "id": "28",
    "name": "Botswana",
    "code": "BW",
    "dial_code": "+267",
    "flag": "🇧🇼",
  },
  {
    "id": "29",
    "name": "Bouvetøya",
    "code": "BV",
    "dial_code": "+47",
    "flag": "🇧🇻",
  },
  {
    "id": "30",
    "name": "Brasil",
    "code": "BR",
    "dial_code": "+55",
    "flag": "🇧🇷",
  },
  {
    "id": "31",
    "name": "British Indian Ocean Territory",
    "code": "IO",
    "dial_code": "+246",
    "flag": "🇮🇴",
  },
  {
    "id": "32",
    "name": "Negara Brunei Darussalam",
    "code": "BN",
    "dial_code": "+673",
    "flag": "🇧🇳",
  },
  {
    "id": "33",
    "name": "България",
    "code": "BG",
    "dial_code": "+359",
    "flag": "🇧🇬",
  },
  {
    "id": "34",
    "name": "Burkina Faso",
    "code": "BF",
    "dial_code": "+226",
    "flag": "🇧🇫",
  },
  {
    "id": "35",
    "name": "Burundi",
    "code": "BI",
    "dial_code": "+257",
    "flag": "🇧🇮",
  },
  {
    "id": "36",
    "name": "Cambodia",
    "code": "KH",
    "dial_code": "+855",
    "flag": "🇰🇭",
  },
  {
    "id": "37",
    "name": "Cameroon",
    "code": "CM",
    "dial_code": "+237",
    "flag": "🇨🇲",
  },
  {
    "id": "38",
    "name": "Canada",
    "code": "CA",
    "dial_code": "+1",
    "flag": "🇨🇦",
  },
  {
    "id": "39",
    "name": "Cabo Verde",
    "code": "CV",
    "dial_code": "+238",
    "flag": "🇨🇻",
  },
  {
    "id": "40",
    "name": "Cayman Islands",
    "code": "KY",
    "dial_code": "+1345",
    "flag": "🇰🇾",
  },
  {
    "id": "41",
    "name": "Ködörösêse tî Bêafrîka",
    "code": "CF",
    "dial_code": "+236",
    "flag": "🇨🇫",
  },
  {
    "id": "42",
    "name": "Tchad",
    "code": "TD",
    "dial_code": "+235",
    "flag": "🇹🇩",
  },
  {
    "id": "43",
    "name": "Chile",
    "code": "CL",
    "dial_code": "+56",
    "flag": "🇨🇱",
  },
  {
    "id": "44",
    "name": "中国",
    "code": "CN",
    "dial_code": "+86",
    "flag": "🇨🇳",
  },
  {
    "id": "45",
    "name": "Christmas Island",
    "code": "CX",
    "dial_code": "+61",
    "flag": "🇨🇽",
  },
  {
    "id": "46",
    "name": "Cocos (Keeling) Islands",
    "code": "CC",
    "dial_code": "+61",
    "flag": "🇨🇨",
  },
  {
    "id": "47",
    "name": "Colombia",
    "code": "CO",
    "dial_code": "+57",
    "flag": "🇨🇴",
  },
  {
    "id": "48",
    "name": "Komori",
    "code": "KM",
    "dial_code": "+269",
    "flag": "🇰🇲",
  },
  {
    "id": "49",
    "name": "République du Congo",
    "code": "CG",
    "dial_code": "+242",
    "flag": "🇨🇬",
  },
  {
    "id": "50",
    "name": "République démocratique du Congo",
    "code": "CD",
    "dial_code": "+243",
    "flag": "🇨🇩",
  },
  {
    "id": "51",
    "name": "Cook Islands",
    "code": "CK",
    "dial_code": "+682",
    "flag": "🇨🇰",
  },
  {
    "id": "52",
    "name": "Costa Rica",
    "code": "CR",
    "dial_code": "+506",
    "flag": "🇨🇷",
  },
  {
    "id": "53",
    "name": "Côte d'Ivoire",
    "code": "CI",
    "dial_code": "+225",
    "flag": "🇨🇮",
  },
  {
    "id": "54",
    "name": "Hrvatska",
    "code": "HR",
    "dial_code": "+385",
    "flag": "🇭🇷",
  },
  {
    "id": "55",
    "name": "Cuba",
    "code": "CU",
    "dial_code": "+53",
    "flag": "🇨🇺",
  },
  {
    "id": "56",
    "name": "Κύπρος",
    "code": "CY",
    "dial_code": "+357",
    "flag": "🇨🇾",
  },
  {
    "id": "57",
    "name": "Česká republika",
    "code": "CZ",
    "dial_code": "+420",
    "flag": "🇨🇿",
  },
  {
    "id": "58",
    "name": "Danmark",
    "code": "DK",
    "dial_code": "+45",
    "flag": "🇩🇰",
  },
  {
    "id": "59",
    "name": "Djibouti",
    "code": "DJ",
    "dial_code": "+253",
    "flag": "🇩🇯",
  },
  {
    "id": "60",
    "name": "Dominica",
    "code": "DM",
    "dial_code": "+1767",
    "flag": "🇩🇲",
  },
  {
    "id": "61",
    "name": "República Dominicana",
    "code": "DO",
    "dial_code": "+1",
    "flag": "🇩🇴",
  },
  {
    "id": "62",
    "name": "Ecuador",
    "code": "EC",
    "dial_code": "+593",
    "flag": "🇪🇨",
  },
  {
    "id": "63",
    "name": "مصر‎",
    "code": "EG",
    "dial_code": "+20",
    "flag": "🇪🇬",
  },
  {
    "id": "64",
    "name": "El Salvador",
    "code": "SV",
    "dial_code": "+503",
    "flag": "🇸🇻",
  },
  {
    "id": "65",
    "name": "Guinea Ecuatorial",
    "code": "GQ",
    "dial_code": "+240",
    "flag": "🇬🇶",
  },
  {
    "id": "66",
    "name": "ኤርትራ",
    "code": "ER",
    "dial_code": "+291",
    "flag": "🇪🇷",
  },
  {
    "id": "67",
    "name": "Eesti",
    "code": "EE",
    "dial_code": "+372",
    "flag": "🇪🇪",
  },
  {
    "id": "68",
    "name": "ኢትዮጵያ",
    "code": "ET",
    "dial_code": "+251",
    "flag": "🇪🇹",
  },
  {
    "id": "69",
    "name": "Falkland Islands",
    "code": "FK",
    "dial_code": "+500",
    "flag": "🇫🇰",
  },
  {
    "id": "70",
    "name": "Føroyar",
    "code": "FO",
    "dial_code": "+298",
    "flag": "🇫🇴",
  },
  {
    "id": "71",
    "name": "Fiji",
    "code": "FJ",
    "dial_code": "+679",
    "flag": "🇫🇯",
  },
  {
    "id": "72",
    "name": "Suomi",
    "code": "FI",
    "dial_code": "+358",
    "flag": "🇫🇮",
  },
  {
    "id": "73",
    "name": "France",
    "code": "FR",
    "dial_code": "+33",
    "flag": "🇫🇷",
  },
  {
    "id": "74",
    "name": "Guyane française",
    "code": "GF",
    "dial_code": "+594",
    "flag": "🇬🇫",
  },
  {
    "id": "75",
    "name": "Polynésie française",
    "code": "PF",
    "dial_code": "+689",
    "flag": "🇵🇫",
  },
  {
    "id": "76",
    "name": "Territoire des Terres australes et antarctiques fr",
    "code": "TF",
    "dial_code": "+262",
    "flag": "🇹🇫",
  },
  {
    "id": "77",
    "name": "Gabon",
    "code": "GA",
    "dial_code": "+241",
    "flag": "🇬🇦",
  },
  {
    "id": "78",
    "name": "Gambia",
    "code": "GM",
    "dial_code": "+220",
    "flag": "🇬🇲",
  },
  {
    "id": "79",
    "name": "საქართველო",
    "code": "GE",
    "dial_code": "+995",
    "flag": "🇬🇪",
  },
  {
    "id": "80",
    "name": "Deutschland",
    "code": "DE",
    "dial_code": "+49",
    "flag": "🇩🇪",
  },
  {
    "id": "81",
    "name": "Ghana",
    "code": "GH",
    "dial_code": "+233",
    "flag": "🇬🇭",
  },
  {
    "id": "82",
    "name": "Gibraltar",
    "code": "GI",
    "dial_code": "+350",
    "flag": "🇬🇮",
  },
  {
    "id": "83",
    "name": "Ελλάδα",
    "code": "GR",
    "dial_code": "+30",
    "flag": "🇬🇷",
  },
  {
    "id": "84",
    "name": "Kalaallit Nunaat",
    "code": "GL",
    "dial_code": "+299",
    "flag": "🇬🇱",
  },
  {
    "id": "85",
    "name": "Grenada",
    "code": "GD",
    "dial_code": "+1473",
    "flag": "🇬🇩",
  },
  {
    "id": "86",
    "name": "Guadeloupe",
    "code": "GP",
    "dial_code": "+590",
    "flag": "🇬🇵",
  },
  {
    "id": "87",
    "name": "Guam",
    "code": "GU",
    "dial_code": "+1671",
    "flag": "🇬🇺",
  },
  {
    "id": "88",
    "name": "Guatemala",
    "code": "GT",
    "dial_code": "+502",
    "flag": "🇬🇹",
  },
  {
    "id": "89",
    "name": "Guernsey",
    "code": "GG",
    "dial_code": "+44",
    "flag": "🇬🇬",
  },
  {
    "id": "90",
    "name": "Guinée",
    "code": "GN",
    "dial_code": "+224",
    "flag": "🇬🇳",
  },
  {
    "id": "91",
    "name": "Guiné-Bissau",
    "code": "GW",
    "dial_code": "+245",
    "flag": "🇬🇼",
  },
  {
    "id": "92",
    "name": "Guyana",
    "code": "GY",
    "dial_code": "+592",
    "flag": "🇬🇾",
  },
  {
    "id": "93",
    "name": "Haïti",
    "code": "HT",
    "dial_code": "+509",
    "flag": "🇭🇹",
  },
  {
    "id": "94",
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "dial_code": "+0",
    "flag": "🇭🇲",
  },
  {
    "id": "95",
    "name": "Vaticano",
    "code": "VA",
    "dial_code": "+379",
    "flag": "🇻🇦",
  },
  {
    "id": "96",
    "name": "Honduras",
    "code": "HN",
    "dial_code": "+504",
    "flag": "🇭🇳",
  },
  {
    "id": "97",
    "name": "香港",
    "code": "HK",
    "dial_code": "+852",
    "flag": "🇭🇰",
  },
  {
    "id": "98",
    "name": "Magyarország",
    "code": "HU",
    "dial_code": "+36",
    "flag": "🇭🇺",
  },
  {
    "id": "99",
    "name": "Ísland",
    "code": "IS",
    "dial_code": "+354",
    "flag": "🇮🇸",
  },
  {
    "id": "100",
    "name": "भारत",
    "code": "IN",
    "dial_code": "+91",
    "flag": "🇮🇳",
  },
  {
    "name": "Indonesia",
    "code": "ID",
    "dial_code": "+62",
    "flag": "🇮🇩",
  },
  {
    "name": "ایران",
    "code": "IR",
    "dial_code": "+98",
    "flag": "🇮🇷",
  },
  {
    "name": "العراق",
    "code": "IQ",
    "dial_code": "+964",
    "flag": "🇮🇶",
  },
  {
    "name": "Éire",
    "code": "IE",
    "dial_code": "+353",
    "flag": "🇮🇪",
  },
  {
    "name": "Isle of Man",
    "code": "IM",
    "dial_code": "+44",
    "flag": "🇮🇲",
  },
  {
    "name": "ישראל",
    "code": "IL",
    "dial_code": "+972",
    "flag": "🇮🇱",
  },
  {
    "name": "Italia",
    "code": "IT",
    "dial_code": "+39",
    "flag": "🇮🇹",
  },
  {
    "name": "Jamaica",
    "code": "JM",
    "dial_code": "+1876",
    "flag": "🇯🇲",
  },
  {
    "name": "日本",
    "code": "JP",
    "dial_code": "+81",
    "flag": "🇯🇵",
  },
  {
    "name": "Jersey",
    "code": "JE",
    "dial_code": "+44",
    "flag": "🇯🇪",
  },
  {
    "name": "الأردن",
    "code": "JO",
    "dial_code": "+962",
    "flag": "🇯🇴",
  },
  {
    "name": "Қазақстан",
    "code": "KZ",
    "dial_code": "+7",
    "flag": "🇰🇿",
  },
  {
    "name": "Kenya",
    "code": "KE",
    "dial_code": "+254",
    "flag": "🇰🇪",
  },
  {
    "name": "Kiribati",
    "code": "KI",
    "dial_code": "+686",
    "flag": "🇰🇮",
  },
  {
    "name": "북한",
    "code": "KP",
    "dial_code": "+850",
    "flag": "🇰🇵",
  },
  {
    "name": "대한민국",
    "code": "KR",
    "dial_code": "+82",
    "flag": "🇰🇷",
  },
  {
    "name": "Republika e Kosovës",
    "code": "XK",
    "dial_code": "+383",
    "flag": "🇽🇰",
  },
  {
    "name": "الكويت",
    "code": "KW",
    "dial_code": "+965",
    "flag": "🇰🇼",
  },
  {
    "name": "Кыргызстан",
    "code": "KG",
    "dial_code": "+996",
    "flag": "🇰🇬",
  },
  {
    "name": "ສປປລາວ",
    "code": "LA",
    "dial_code": "+856",
    "flag": "🇱🇦",
  },
  {
    "name": "Latvija",
    "code": "LV",
    "dial_code": "+371",
    "flag": "🇱🇻",
  },
  {
    "name": "لبنان",
    "code": "LB",
    "dial_code": "+961",
    "flag": "🇱🇧",
  },
  {
    "name": "Lesotho",
    "code": "LS",
    "dial_code": "+266",
    "flag": "🇱🇸",
  },
  {
    "name": "Liberia",
    "code": "LR",
    "dial_code": "+231",
    "flag": "🇱🇷",
  },
  {
    "name": "‏ليبيا",
    "code": "LY",
    "dial_code": "+218",
    "flag": "🇱🇾",
  },
  {
    "name": "Liechtenstein",
    "code": "LI",
    "dial_code": "+423",
    "flag": "🇱🇮",
  },
  {
    "name": "Lietuva",
    "code": "LT",
    "dial_code": "+370",
    "flag": "🇱🇹",
  },
  {
    "name": "Luxembourg",
    "code": "LU",
    "dial_code": "+352",
    "flag": "🇱🇺",
  },
  {
    "name": "澳門",
    "code": "MO",
    "dial_code": "+853",
    "flag": "🇲🇴",
  },
  {
    "name": "Македонија",
    "code": "MK",
    "dial_code": "+389",
    "flag": "🇲🇰",
  },
  {
    "name": "Madagasikara",
    "code": "MG",
    "dial_code": "+261",
    "flag": "🇲🇬",
  },
  {
    "name": "Malawi",
    "code": "MW",
    "dial_code": "+265",
    "flag": "🇲🇼",
  },
  {
    "name": "Malaysia",
    "code": "MY",
    "dial_code": "+60",
    "flag": "🇲🇾",
  },
  {
    "name": "Maldives",
    "code": "MV",
    "dial_code": "+960",
    "flag": "🇲🇻",
  },
  {
    "name": "Mali",
    "code": "ML",
    "dial_code": "+223",
    "flag": "🇲🇱",
  },
  {
    "name": "Malta",
    "code": "MT",
    "dial_code": "+356",
    "flag": "🇲🇹",
  },
  {
    "name": "M̧ajeļ",
    "code": "MH",
    "dial_code": "+692",
    "flag": "🇲🇭",
  },
  {
    "name": "Martinique",
    "code": "MQ",
    "dial_code": "+596",
    "flag": "🇲🇶",
  },
  {
    "name": "موريتانيا",
    "code": "MR",
    "dial_code": "+222",
    "flag": "🇲🇷",
  },
  {
    "name": "Maurice",
    "code": "MU",
    "dial_code": "+230",
    "flag": "🇲🇺",
  },
  {
    "name": "Mayotte",
    "code": "YT",
    "dial_code": "+262",
    "flag": "🇾🇹",
  },
  {
    "name": "México",
    "code": "MX",
    "dial_code": "+52",
    "flag": "🇲🇽",
  },
  {
    "name": "Micronesia",
    "code": "FM",
    "dial_code": "+691",
    "flag": "🇫🇲",
  },
  {
    "name": "Moldova",
    "code": "MD",
    "dial_code": "+373",
    "flag": "🇲🇩",
  },
  {
    "name": "Monaco",
    "code": "MC",
    "dial_code": "+377",
    "flag": "🇲🇨",
  },
  {
    "name": "Монгол улс",
    "code": "MN",
    "dial_code": "+976",
    "flag": "🇲🇳",
  },
  {
    "name": "Црна Гора",
    "code": "ME",
    "dial_code": "+382",
    "flag": "🇲🇪",
  },
  {
    "name": "Montserrat",
    "code": "MS",
    "dial_code": "+1664",
    "flag": "🇲🇸",
  },
  {
    "name": "المغرب",
    "code": "MA",
    "dial_code": "+212",
    "flag": "🇲🇦",
  },
  {
    "name": "Moçambique",
    "code": "MZ",
    "dial_code": "+258",
    "flag": "🇲🇿",
  },
  {
    "name": "Myanmar",
    "code": "MM",
    "dial_code": "+95",
    "flag": "🇲🇲",
  },
  {
    "name": "Namibia",
    "code": "NA",
    "dial_code": "+264",
    "flag": "🇳🇦",
  },
  {
    "name": "Nauru",
    "code": "NR",
    "dial_code": "+674",
    "flag": "🇳🇷",
  },
  {
    "name": "नेपाल",
    "code": "NP",
    "dial_code": "+977",
    "flag": "🇳🇵",
  },
  {
    "name": "Nederland",
    "code": "NL",
    "dial_code": "+31",
    "flag": "🇳🇱",
  },
  {
    "name": "Netherlands Antilles",
    "code": "AN",
    "dial_code": "+599",
    "flag": "🇦🇳",
  },
  {
    "name": "Nouvelle-Calédonie",
    "code": "NC",
    "dial_code": "+687",
    "flag": "🇳🇨",
  },
  {
    "name": "New Zealand",
    "code": "NZ",
    "dial_code": "+64",
    "flag": "🇳🇿",
  },
  {
    "name": "Nicaragua",
    "code": "NI",
    "dial_code": "+505",
    "flag": "🇳🇮",
  },
  {
    "name": "Niger",
    "code": "NE",
    "dial_code": "+227",
    "flag": "🇳🇪",
  },
  {
    "name": "Nigeria",
    "code": "NG",
    "dial_code": "+234",
    "flag": "🇳🇬",
  },
  {
    "name": "Niuē",
    "code": "NU",
    "dial_code": "+683",
    "flag": "🇳🇺",
  },
  {
    "name": "Norfolk Island",
    "code": "NF",
    "dial_code": "+672",
    "flag": "🇳🇫",
  },
  {
    "name": "Northern Mariana Islands",
    "code": "MP",
    "dial_code": "+1670",
    "flag": "🇲🇵",
  },
  {
    "name": "Norge",
    "code": "NO",
    "dial_code": "+47",
    "flag": "🇳🇴",
  },
  {
    "name": "عمان",
    "code": "OM",
    "dial_code": "+968",
    "flag": "🇴🇲",
  },
  {
    "name": "Pakistan",
    "code": "PK",
    "dial_code": "+92",
    "flag": "🇵🇰",
  },
  {
    "name": "Palau",
    "code": "PW",
    "dial_code": "+680",
    "flag": "🇵🇼",
  },
  {
    "name": "فلسطين",
    "code": "PS",
    "dial_code": "+970",
    "flag": "🇵🇸",
  },
  {
    "name": "Panamá",
    "code": "PA",
    "dial_code": "+507",
    "flag": "🇵🇦",
  },
  {
    "name": "Papua Niugini",
    "code": "PG",
    "dial_code": "+675",
    "flag": "🇵🇬",
  },
  {
    "name": "Paraguay",
    "code": "PY",
    "dial_code": "+595",
    "flag": "🇵🇾",
  },
  {
    "name": "Perú",
    "code": "PE",
    "dial_code": "+51",
    "flag": "🇵🇪",
  },
  {
    "name": "Pilipinas",
    "code": "PH",
    "dial_code": "+63",
    "flag": "🇵🇭",
  },
  {
    "name": "Pitcairn Islands",
    "code": "PN",
    "dial_code": "+64",
    "flag": "🇵🇳",
  },
  {
    "name": "Polska",
    "code": "PL",
    "dial_code": "+48",
    "flag": "🇵🇱",
  },
  {
    "name": "Portugal",
    "code": "PT",
    "dial_code": "+351",
    "flag": "🇵🇹",
  },
  {
    "name": "Puerto Rico",
    "code": "PR",
    "dial_code": "+1939",
    "flag": "🇵🇷",
  },
  {
    "name": "Puerto Rico",
    "code": "PR",
    "dial_code": "+1787",
    "flag": "🇵🇷",
  },
  {
    "name": "قطر",
    "code": "QA",
    "dial_code": "+974",
    "flag": "🇶🇦",
  },
  {
    "name": "România",
    "code": "RO",
    "dial_code": "+40",
    "flag": "🇷🇴",
  },
  {
    "name": "Россия",
    "code": "RU",
    "dial_code": "+7",
    "flag": "🇷🇺",
  },
  {
    "name": "Rwanda",
    "code": "RW",
    "dial_code": "+250",
    "flag": "🇷🇼",
  },
  {
    "name": "La Réunion",
    "code": "RE",
    "dial_code": "+262",
    "flag": "🇷🇪",
  },
  {
    "name": "Saint-Barthélemy",
    "code": "BL",
    "dial_code": "+590",
    "flag": "🇧🇱",
  },
  {
    "name": "Saint Helena",
    "code": "SH",
    "dial_code": "+290",
    "flag": "🇸🇭",
  },
  {
    "name": "Saint Kitts and Nevis",
    "code": "KN",
    "dial_code": "+1869",
    "flag": "🇰🇳",
  },
  {
    "name": "Saint Lucia",
    "code": "LC",
    "dial_code": "+1758",
    "flag": "🇱🇨",
  },
  {
    "name": "Saint-Martin",
    "code": "MF",
    "dial_code": "+590",
    "flag": "🇲🇫",
  },
  {
    "name": "Saint-Pierre-et-Miquelon",
    "code": "PM",
    "dial_code": "+508",
    "flag": "🇵🇲",
  },
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "dial_code": "+1784",
    "flag": "🇻🇨",
  },
  {
    "name": "Samoa",
    "code": "WS",
    "dial_code": "+685",
    "flag": "🇼🇸",
  },
  {
    "name": "San Marino",
    "code": "SM",
    "dial_code": "+378",
    "flag": "🇸🇲",
  },
  {
    "name": "São Tomé e Príncipe",
    "code": "ST",
    "dial_code": "+239",
    "flag": "🇸🇹",
  },
  {
    "name": "العربية السعودية",
    "code": "SA",
    "dial_code": "+966",
    "flag": "🇸🇦",
  },
  {
    "name": "Sénégal",
    "code": "SN",
    "dial_code": "+221",
    "flag": "🇸🇳",
  },
  {
    "name": "Србија",
    "code": "RS",
    "dial_code": "+381",
    "flag": "🇷🇸",
  },
  {
    "name": "Seychelles",
    "code": "SC",
    "dial_code": "+248",
    "flag": "🇸🇨",
  },
  {
    "name": "Sierra Leone",
    "code": "SL",
    "dial_code": "+232",
    "flag": "🇸🇱",
  },
  {
    "name": "Singapore",
    "code": "SG",
    "dial_code": "+65",
    "flag": "🇸🇬",
  },
  {
    "name": "Slovensko",
    "code": "SK",
    "dial_code": "+421",
    "flag": "🇸🇰",
  },
  {
    "name": "Slovenija",
    "code": "SI",
    "dial_code": "+386",
    "flag": "🇸🇮",
  },
  {
    "name": "Solomon Islands",
    "code": "SB",
    "dial_code": "+677",
    "flag": "🇸🇧",
  },
  {
    "name": "Soomaaliya",
    "code": "SO",
    "dial_code": "+252",
    "flag": "🇸🇴",
  },
  {
    "name": "South Africa",
    "code": "ZA",
    "dial_code": "+27",
    "flag": "🇿🇦",
  },
  {
    "name": "South Sudan",
    "code": "SS",
    "dial_code": "+211",
    "flag": "🇸🇸",
  },
  {
    "name": "South Georgia",
    "code": "GS",
    "dial_code": "+500",
    "flag": "🇬🇸",
  },
  {
    "name": "España",
    "code": "ES",
    "dial_code": "+34",
    "flag": "🇪🇸",
  },
  {
    "name": "Sri Lanka",
    "code": "LK",
    "dial_code": "+94",
    "flag": "🇱🇰",
  },
  {
    "name": "السودان",
    "code": "SD",
    "dial_code": "+249",
    "flag": "🇸🇩",
  },
  {
    "name": "Suriname",
    "code": "SR",
    "dial_code": "+597",
    "flag": "🇸🇷",
  },
  {
    "name": "Svalbard og Jan Mayen",
    "code": "SJ",
    "dial_code": "+47",
    "flag": "🇸🇯",
  },
  {
    "name": "Swaziland",
    "code": "SZ",
    "dial_code": "+268",
    "flag": "🇸🇿",
  },
  {
    "name": "Sverige",
    "code": "SE",
    "dial_code": "+46",
    "flag": "🇸🇪",
  },
  {
    "name": "Schweiz",
    "code": "CH",
    "dial_code": "+41",
    "flag": "🇨🇭",
  },
  {
    "name": "سوريا",
    "code": "SY",
    "dial_code": "+963",
    "flag": "🇸🇾",
  },
  {
    "name": "臺灣",
    "code": "TW",
    "dial_code": "+886",
    "flag": "🇹🇼",
  },
  {
    "name": "Тоҷикистон",
    "code": "TJ",
    "dial_code": "+992",
    "flag": "🇹🇯",
  },
  {
    "name": "Tanzania",
    "code": "TZ",
    "dial_code": "+255",
    "flag": "🇹🇿",
  },
  {
    "name": "ประเทศไทย",
    "code": "TH",
    "dial_code": "+66",
    "flag": "🇹🇭",
  },
  {
    "name": "Timor-Leste",
    "code": "TL",
    "dial_code": "+670",
    "flag": "🇹🇱",
  },
  {
    "name": "Togo",
    "code": "TG",
    "dial_code": "+228",
    "flag": "🇹🇬",
  },
  {
    "name": "Tokelau",
    "code": "TK",
    "dial_code": "+690",
    "flag": "🇹🇰",
  },
  {
    "name": "Tonga",
    "code": "TO",
    "dial_code": "+676",
    "flag": "🇹🇴",
  },
  {
    "name": "Trinidad and Tobago",
    "code": "TT",
    "dial_code": "+1868",
    "flag": "🇹🇹",
  },
  {
    "name": "تونس",
    "code": "TN",
    "dial_code": "+216",
    "flag": "🇹🇳",
  },
  {
    "name": "Türkiye",
    "code": "TR",
    "dial_code": "+90",
    "flag": "🇹🇷",
  },
  {
    "name": "Türkmenistan",
    "code": "TM",
    "dial_code": "+993",
    "flag": "🇹🇲",
  },
  {
    "name": "Turks and Caicos Islands",
    "code": "TC",
    "dial_code": "+1649",
    "flag": "🇹🇨",
  },
  {
    "name": "Tuvalu",
    "code": "TV",
    "dial_code": "+688",
    "flag": "🇹🇻",
  },
  {
    "name": "Uganda",
    "code": "UG",
    "dial_code": "+256",
    "flag": "🇺🇬",
  },
  {
    "name": "Україна",
    "code": "UA",
    "dial_code": "+380",
    "flag": "🇺🇦",
  },
  {
    "name": "دولة الإمارات العربية المتحدة",
    "code": "AE",
    "dial_code": "+971",
    "flag": "🇦🇪",
  },
  {
    "name": "United Kingdom",
    "code": "GB",
    "dial_code": "+44",
    "flag": "🇬🇧",
  },
  {
    "name": "United States",
    "code": "US",
    "dial_code": "+1",
    "flag": "🇺🇸",
  },
  {
    "name": "Uruguay",
    "code": "UY",
    "dial_code": "+598",
    "flag": "🇺🇾",
  },
  {
    "name": "O‘zbekiston",
    "code": "UZ",
    "dial_code": "+998",
    "flag": "🇺🇿",
  },
  {
    "name": "Vanuatu",
    "code": "VU",
    "dial_code": "+678",
    "flag": "🇻🇺",
  },
  {
    "name": "Venezuela",
    "code": "VE",
    "dial_code": "+58",
    "flag": "🇻🇪",
  },
  {
    "name": "Việt Nam",
    "code": "VN",
    "dial_code": "+84",
    "flag": "🇻🇳",
  },
  {
    "name": "British Virgin Islands",
    "code": "VG",
    "dial_code": "+1284",
    "flag": "🇻🇬",
  },
  {
    "name": "United States Virgin Islands",
    "code": "VI",
    "dial_code": "+1340",
    "flag": "🇻🇮",
  },
  {
    "name": "Wallis et Futuna",
    "code": "WF",
    "dial_code": "+681",
    "flag": "🇼🇫",
  },
  {
    "name": "اليَمَن",
    "code": "YE",
    "dial_code": "+967",
    "flag": "🇾🇪",
  },
  {
    "name": "Zambia",
    "code": "ZM",
    "dial_code": "+260",
    "flag": "🇿🇲",
  },
  {
    "name": "Zimbabwe",
    "code": "ZW",
    "dial_code": "+263",
    "flag": "🇿🇼",
  },
];
